
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramhari
 */
public class PdfFileManagement extends javax.swing.JFrame {

    /**
     * Creates new form PdfFileManagement
     */
    public PdfFileManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocation = new javax.swing.JTextField();
        txtFilename = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFileExtension = new javax.swing.JTextField();
        btnFileSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListOfFiles = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        txtLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocation);
        txtLocation.setBounds(22, 66, 700, 30);
        getContentPane().add(txtFilename);
        txtFilename.setBounds(22, 104, 219, 30);

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(248, 103, 79, 25);

        jLabel1.setText("Enter location of file");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 43, 332, 10);
        getContentPane().add(txtFileExtension);
        txtFileExtension.setBounds(30, 200, 220, 30);

        btnFileSearch.setText("SEARCH");
        btnFileSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFileSearchMouseClicked(evt);
            }
        });
        getContentPane().add(btnFileSearch);
        btnFileSearch.setBounds(30, 240, 220, 25);

        txtListOfFiles.setColumns(20);
        txtListOfFiles.setRows(5);
        jScrollPane1.setViewportView(txtListOfFiles);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 200, 440, 150);

        jLabel2.setText("List of searched files:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 180, 290, 16);

        jLabel4.setBackground(new java.awt.Color(0, 153, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramhari\\Pictures\\Saved Pictures\\uu.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 770, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        try{
        File file=new File(txtLocation.getText() + "/" + txtFilename.getText());
        boolean result = file.createNewFile();
        if(result==true)
        {
            JOptionPane.showInternalMessageDialog(null,"File created successfully");
        }
        else
        {
            JOptionPane.showInternalMessageDialog(null,"File already Exists");
        }
        
    }//GEN-LAST:event_btnCreateMouseClicked
catch(Exception ex)
{
    JOptionPane.showInternalMessageDialog(null,"Sorry,file not created");
}
    }
    private void btnFileSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFileSearchMouseClicked
        // TODO add your handling code here:
        
        File folder=new File(txtLocation.getText());
        if(folder.isDirectory()==true)
        {
            String[] files=folder.list();
            String fileNames="";
            for(int i=0;i<files.length;i++)
            {
                int index=files[i].indexOf(".");
                String extension;
                extension = files[i].substring(index+i);
                
                if(txtFileExtension.getText().equals(extension)==true)
                {
                fileNames+="\n"+files[i];
            }
            }
            
            txtListOfFiles.setText(fileNames);
        }
    }//GEN-LAST:event_btnFileSearchMouseClicked

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PdfFileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PdfFileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PdfFileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PdfFileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PdfFileManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFileSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFileExtension;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextArea txtListOfFiles;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
